---
title: "text_analysis"
author: "Lily Diao"
date: "4/16/2021"
output: html_document
---

```{r setup, include=FALSE}
# # Install
# install.packages("tm")  # for text mining
# install.packages("SnowballC") # for text stemming
# install.packages("wordcloud") # word-cloud generator 
# install.packages("RColorBrewer") # color palettes
# # Load
# library("tm")
# library("SnowballC")
# library("wordcloud")
# library("RColorBrewer")
library(tidyverse)
library(dplyr)
library(tidytext)
library(tidyverse)
library(plotly)
library(lubridate)
library(ggplot2)
library(png)
library(grid)
library(rgdal)
library(raster)
library(sp)
library(spdep)
library(conflicted)
```


```{r}
text<-read.csv("YInt.csv")
```

```{r}
# data wrangling of text message
text_only<-text %>% 
  dplyr::select(message)

text_only$message<-as.character(text_only$message)
text_only$line <- seq.int(nrow(text_only))
```

```{r}
# breaking up text and stop words
text_only<-text_only %>%
  unnest_tokens(word, message)
data(stop_words)
text_only <- text_only %>%
  anti_join(stop_words)
text_only
```

```{r}
text_only %>% 
  count(word, sort = TRUE)
text_only_count <-text_only %>% 
  group_by(word) %>% 
  summarise(count=n()) %>% 
  arrange(desc(count))
text_only_count         
  
```

```{r}
# bigram analysis
text_bigram<-text %>% 
  select(message)
text_bigram$message<-as.character(text_bigram$message)
text_bigram$line <- seq.int(nrow(text_bigram))
text_bigram <- text_bigram %>%
  unnest_tokens(bigram, message, token = "ngrams", n = 2)

text_bigram_separated <- text_bigram %>%
  separate(bigram, c("word1", "word2"), sep = " ")

text_bigrams_filtered <-text_bigram_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts:
bigram_counts <- text_bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)
bigram_counts
```

```{r}
# word cloud
set.seed(1234)
wordcloud(words = text_only_count$word, freq = text_only_count$count, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```


